import Head from 'next/head'

export default function Contact() {
  return (
    <>
      <Head>
        <title>Simple Next Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Contact</h1>
    </>
  )
}